source "https://rubygems.org"

gem "rake"
gem "puppet", ENV['PUPPET_VERSION'] || '~> 3.8.0'
gem "rspec-puppet", '~> 2.2.0'
gem "puppetlabs_spec_helper"
gem 'rspec-puppet-utils'
gem 'hiera-puppet-helper'
gem "travis"
gem "travis-lint"
gem "puppet-blacksmith"
gem "guard-rake"
gem "metadata-json-lint"
gem 'puppet-syntax'
gem 'guard'
gem 'rb-inotify', :require => false
gem 'rb-fsevent', :require => false
gem 'rb-fchange', :require => false
gem 'growl', :require => false
gem 'libnotify', :require => false
gem 'guard-rspec'
gem 'guard-cucumber'
#gem 'puppet-retrospec', '~> 0.7'

